# This is a basic workflow to help you get started with Actions

name: Add a Reviewer based on label

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types:
      - labeled

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  add_reviewer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Add reviewer
        uses: actions/github-script@v3
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          script: |
            const issue_number = context.issue.number;
            if (context.payload.label.name === 'Design') {
              github.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: issue_number,
                reviewers: ['@pranshudobhal']
              }) 
            }
