name: Remove a Reviewer based on label

on:
  pull_request:
    types: 
      - unlabeled

jobs:
  remove_reviewer:
    runs-on: ubuntu-latest
    steps:
    - name: Remove Reviewer
      uses: actions/github-script@v6
      with:
        script: |
          const issue_number = context.issue.number;
          if (context.payload.label.name === 'Design') {
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: issue_number
            });
          const reviewersToRemove = pullRequest.requested_reviewers.filter(reviewer => reviewer.login === 'lavanyasengar22');
          github.rest.pulls.removeRequestedReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: issue_number,
              reviewers: reviewersToRemove.map(reviewer => reviewer.login)
            })
          }
